import { NgModule } from '@angular/core';
import { NoopScrollStrategy } from '@angular/cdk/overlay';

import {
  MatMenuModule,
  MatIconModule,
  MatCardModule,
  MatSelectModule,
  MatRadioModule,
  MatTooltipModule,
  MatButtonModule,
  MatToolbarModule,
  MatExpansionModule,
  MatListModule,
  MatProgressSpinnerModule,
  MatDialogModule,
  MatChipsModule,
  MatInputModule,
  MatAutocompleteModule,
  MatTabsModule,
  MatSlideToggleModule,
  MatFormFieldModule,
  MatCheckboxModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatProgressBarModule,
  MAT_DIALOG_SCROLL_STRATEGY,
  MatSliderModule,
  MatGridListModule,
  MatSidenavModule,
  MatTableModule,
  MatSortModule,
  MatSnackBarModule,
} from '@angular/material';

@NgModule({
  imports: [
    MatMenuModule,
    MatButtonModule,
    MatIconModule,
    MatTooltipModule,
    MatCardModule,
    MatSelectModule,
    MatRadioModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatChipsModule,
    MatInputModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatSlideToggleModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatNativeDateModule,
    MatProgressBarModule,
    MatSliderModule,
    MatGridListModule,
    MatSidenavModule,
    MatTableModule,
    MatSortModule,
    MatSnackBarModule,
  ],
  exports: [
    MatTooltipModule,
    MatMenuModule,
    MatButtonModule,
    MatIconModule,
    MatTooltipModule,
    MatCardModule,
    MatSelectModule,
    MatRadioModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatChipsModule,
    MatInputModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatSlideToggleModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatProgressBarModule,
    MatSliderModule,
    MatGridListModule,
    MatSidenavModule,
    MatTableModule,
    MatSortModule,
    MatSnackBarModule,
  ],
  providers: [MatNativeDateModule, { provide: MAT_DIALOG_SCROLL_STRATEGY, useValue: NoopScrollStrategy }],
})
export class MaterialModule {}
